package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.AmazonEC2CloudImage
import jetbrains.buildServer.configs.kotlin.AmazonEC2CloudProfile
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.amazonEC2CloudImage
import jetbrains.buildServer.configs.kotlin.amazonEC2CloudProfile
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'JavaMavenDemo'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("JavaMavenDemo")) {
    features {
        val feature1 = find<AmazonEC2CloudImage> {
            amazonEC2CloudImage {
                id = "PROJECT_EXT_356"
                profileId = "amazon-20"
                agentPoolId = "253fhufifhu"
                imagePriority = 3
                name = "Instance Image (new)"
                vpcSubnetId = "subnet-0c23f411b0800b216"
                keyPairName = "daria.krupkina"
                instanceType = "t2.medium"
                securityGroups = listOf("sg-072d8bfa0626ea2a6")
                source = Source("i-0aa8f308327fd1bc1")
            }
        }
        feature1.apply {
            profileId = "amazon-20"
            agentPoolId = "-2"
            imagePriority = 3
            name = "Instance Image (new)"
            vpcSubnetId = "subnet-0c23f411b0800b216"
            keyPairName = "daria.krupkina"
            instanceType = "t2.medium"
            securityGroups = listOf("sg-072d8bfa0626ea2a6")
            source = Source("i-0aa8f308327fd1bc1")
        }
        val feature2 = find<AmazonEC2CloudImage> {
            amazonEC2CloudImage {
                id = "PROJECT_EXT_NEW_AM"
                profileId = "amazon-20"
                agentPoolId = "433391"
                imagePriority = 10
                name = "Ubuntu AMI (incorrect pool from the start)"
                vpcSubnetId = "subnet-0ee5ddb298ed3d189"
                iamProfile = "dkrupkinaEc2Role"
                keyPairName = "daria.krupkina"
                instanceType = "t2.small"
                securityGroups = listOf("sg-072d8bfa0626ea2a6")
                useSpotInstances = true
                spotInstanceBidPrice = 0.02
                instanceTags = mapOf(
                    "Owner" to "daria.krupkina@jetbrains.com"
                )
                maxInstancesCount = 1
                source = Source("ami-0817025aa39c203c6")
            }
        }
        feature2.apply {
            profileId = "amazon-20"
            agentPoolId = "-2"
            imagePriority = 10
            name = "Ubuntu AMI (incorrect pool from the start)"
            vpcSubnetId = "subnet-0ee5ddb298ed3d189"
            iamProfile = "dkrupkinaEc2Role"
            keyPairName = "daria.krupkina"
            instanceType = "t2.small"
            securityGroups = listOf("sg-072d8bfa0626ea2a6")
            useSpotInstances = true
            spotInstanceBidPrice = 0.02
            instanceTags = mapOf(
                "Owner" to "daria.krupkina@jetbrains.com"
            )
            maxInstancesCount = 1
            source = Source("ami-0817025aa39c203c6")
        }
        val feature3 = find<AmazonEC2CloudProfile> {
            amazonEC2CloudProfile {
                id = "amazon-22"
                enabled = false
                name = "AWS EC2: keys"
                description = "AWS EC2 Cloud Profile with access keys authentication."
                terminateIdleMinutes = 0
                terminateTotalWorkMinutes = 30
                region = AmazonEC2CloudProfile.Regions.EU_WEST_DUBLIN
                awsConnectionId = "AwsEc2Profile_JavaMavenDemo_AmazonWebServicesAwsKeys"
            }
        }
        feature3.apply {
            name = "AWS EC2: keys"
            description = "AWS EC2 Cloud Profile with access keys authentication."
            terminateIdleMinutes = 0
            terminateTotalWorkMinutes = 30
            region = AmazonEC2CloudProfile.Regions.EU_WEST_DUBLIN
            awsConnectionId = "AwsEc2Profile_JavaMavenDemo_AmazonWebServicesAwsKeys"
        }
    }
}
