package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.AmazonEC2CloudImage
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.amazonEC2CloudImage
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'JavaMavenDemo'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("JavaMavenDemo")) {
    features {
        val feature1 = find<AmazonEC2CloudImage> {
            amazonEC2CloudImage {
                id = "PROJECT_EXT_356"
                profileId = "amazon-20"
                agentPoolId = "253fhufifhu"
                imagePriority = 3
                name = "Instance Image (new)"
                vpcSubnetId = "subnet-0c23f411b0800b216"
                keyPairName = "daria.krupkina"
                instanceType = "t2.medium"
                securityGroups = listOf("sg-072d8bfa0626ea2a6")
                source = Source("i-0aa8f308327fd1bc1")
            }
        }
        feature1.apply {
            profileId = "amazon-20"
            agentPoolId = "-2"
            imagePriority = 3
            name = "Instance Image (new)"
            vpcSubnetId = "subnet-0c23f411b0800b216"
            keyPairName = "daria.krupkina"
            instanceType = "t2.medium"
            securityGroups = listOf("sg-072d8bfa0626ea2a6")
            source = Source("i-0aa8f308327fd1bc1")
        }
    }
}
