package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.AwsConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.S3Storage
import jetbrains.buildServer.configs.kotlin.projectFeatures.awsConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.s3Storage
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<AwsConnection> {
            awsConnection {
                id = "MavenUnbalancedMessages_AmazonWebServicesAws"
                name = "Amazon Web Services (AWS)"
                regionName = "eu-west-1"
                credentialsType = static {
                    accessKeyId = "AKIA5JH2VERVI62P5XDY"
                    secretAccessKey = "credentialsJSON:eb053465-ece1-444c-af16-96f1ad63ccff"
                }
                allowInSubProjects = true
                allowInBuilds = true
                stsEndpoint = "https://sts.eu-west-1.amazonaws.com"
            }
        }
        feature1.apply {
            regionName = "eu-south-1"
            stsEndpoint = "https://sts.eu-south-1.amazonaws.com"
            param("awsSessionDuration", "")
        }
        val feature2 = find<S3Storage> {
            s3Storage {
                id = "PROJECT_EXT_2"
                storageName = "S3"
                bucketName = "tc-dkrupkina-limited-access"
                bucketPrefix = "maven-s3"
                forceVirtualHostAddressing = true
                awsEnvironment = default {
                }
                connectionId = "MavenUnbalancedMessages_AmazonWebServicesAws"
            }
        }
        feature2.apply {
            bucketName = "tc-dkrupkina-acceleration"
            awsEnvironment = default {
                awsRegionName = "eu-west-1"
            }
        }
    }
}
